Add multiarch build
AppDaemon/appdaemon pull request #1080
Opened 2020-11-30 19:37 UTC by lexfrei

Important! Add CR_PAT (container registry personal access token) to repo secrets. Required permissions: packages:*

- Building on each push. Add the desired config, example: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#on
- Current tagging: commit sha and branch name (ex.: sha-8a83892, dev)
- Change image repository to the desired one at L:12
- GitHub Container registry used. Feel free to change it on L:27
- ARM64/AMD64 build enabled. Add more on L:36

2020-11-30 19:37 UTC, lexfrei commented
Replacing: #1022

2021-01-11 15:25 UTC, Odianosen25 commented
Hello @lexfrei,

Thanks for this. Just moving via the PRs and wanted to ask a favour from yours.

There is a section of users who prefer a Debain based one (for good reason), compared to the Alpine which is default. Will it be possible please, to have a multi arch build for both?

What will it entail?

Kind regards

2021-01-12 12:26 UTC, lexfrei commented
@Odianosen25 this CI is not about alpine-only. It refers to Dockerfile on the root of the project and just builds it. I can't create a proper Dockerfile for debiand-based images just coz I'm not similar to deb-world and cant suggest how to make a good one.

2021-01-12 13:48 UTC, Odianosen25 commented
Hello @lexfrei,

Thanks for the response, and I am sorry to drag this a little, but I am trying to find solution to something. There is a PR [here](https://github.com/AppDaemon/appdaemon/pull/1118), which seeks to make use of deb as base image, and I kind of understand if some users want a deb, due to it being easier.

From what you saying, seems you are an alpine person, which I am also, but I will like AD users to have both worlds if they can. So if you saying all your script does is make use of the existing docker file and build on that. Is it possible in anyway, to make use of the PR submitted to make both builds?

 Kind regards

2021-01-26 13:57 UTC, benleb commented
> From what you saying, seems you are an alpine person, which I am also, but I will like AD users to have both worlds if they can. So if you saying all your script does is make use of the existing docker file and build on that. Is it possible in anyway, to make use of the PR submitted to make both builds?

Hey, I would suggest two separate Dockerfiles, `debian.Dockerfile` and `alpine.Dockerfile`, which will then be built by a github workflow. And yes, building both is no problem... in this case you would just have do duplicate the block in the yaml starting with "  build:" (below "jobs:") and specify the Dockerfiles in each of them. See you in discord :D

2021-01-26 14:16 UTC, benleb requested changes
A more up-to-date version of my PR (#1022) 👍  But I would suggest including the other archs as this has no downsides but makes it possible to use the images on old RPis. Should not make any problems, I am building appdaemon for it since months without issues 👍

2021-01-26 14:16 UTC, benleb commented on .github/workflows/docker.yml
> +        platforms: linux/amd64,linux/arm64
lets also add `linux/arm/v7,linux/arm/v6` for compatibility with old Pis for example.

2021-01-26 15:28 UTC, lexfrei commented
@benleb added

2021-01-26 16:35 UTC, benleb approved these changes

2021-01-26 17:00 UTC, lexfrei commented
Don't merge. Let me bump action versions

2021-01-26 17:15 UTC, Odianosen25 commented
Thanks for the work on this guys, really appreciate it. @lexfrei just let me know when you done then will look into merging sometime later today or tomorrow, once I get my head around it all.

kind regards

2021-01-26 17:32 UTC, lexfrei commented
@Odianosen25 looks done for me.
Also, the registry was changed to the suggested one. Feel free to change it again

2021-01-26 17:53 UTC, lexfrei commented
Also, I can suggest using depandabot for GH actions to keep actions updated.

Create `.github/dependabot.yml` with similar content:

```yaml
version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
```

Or add GH Actions to the job list on dependabot site.

2021-01-26 18:40 UTC, benleb commented
As that's completely independent it should get its own PR 👍

2021-01-26 19:19 UTC, lexfrei commented
@benleb just wild guess :) I got no idea how dependabot configured right now for the project, but it needs adjustment to update the action from this PR

2021-01-26 21:25 UTC, merged

2021-01-26 21:31 UTC, lexfrei commented
@Odianosen25 add token as CR_PAT in repo config and rerun job

2021-01-26 21:56 UTC, Odianosen25 commented
@lexfrei,

Was just reminded abt that, will be worked on as I need to discuss it with Andrew on how he wants the secret to be created.

I am sure he will look into it once he comes on line.

Regards

2021-02-07 18:33 UTC, nicolaerosia commented
is the CI pushing arm64 images now? If yes, where?

2021-02-07 18:47 UTC, Odianosen25 commented
No @nicolaerosia, unfortunately its still failing but @acockburn is looking into it.

Regards

2021-03-16 16:52 UTC, Enf0 commented
Any updates on this? Is there an arm64 image of AppDaemon available?

2021-05-10 21:11 UTC, benleb commented
until then, you can use mine if you want, stripped down and arm64 available ✌️

https://github.com/benleb/appdaemon
https://hub.docker.com/r/benleb/appdaemon

2021-05-11 07:22 UTC, emilp333 commented
Thanks! I will try it :)