add the ability to automaticly add custom javascript to dashboards
AppDaemon/appdaemon pull request #1165
Opened 2021-02-18 00:10 UTC by ReneTode

creates a route for config/custom_javascript

adds all JS files from that route automaticly to the head includes

js files can already be included in the head by adding them to the skin, this option makes it possible to use js files in all skins.

2021-02-18 11:44 UTC, Odianosen25 requested changes

2021-02-18 11:51 UTC, ReneTode commented on appdaemon/http.py
> +        custom_javascript = os.path.join(self.dashboard_obj.config_dir, "custom_javascript")
i just copied the lines that were there for custom_css

i expect that the check is done BEFORE setup_dashboard_routes is called.
the other change is in dashboard.py, so i guess there shouldnt be a check there either.
so i dont know where you want me to place a check

2021-02-18 12:13 UTC, Odianosen25 commented
Now we need to figure out why these changes are not passing checks

2021-02-18 12:29 UTC, frenck commented
black...

2021-02-18 12:47 UTC, ReneTode commented
i got no clue.

and black isnt telling me anything ;)

2021-02-18 12:59 UTC, frenck commented
![image](https://user-images.githubusercontent.com/195327/108360402-76da3100-71f1-11eb-8d6d-1954a463436f.png)

You need to format the code with black. Additionally, if you set up pre-commit correctly, this will be done on commit automatically (prevents you from running into these issues for the future).

2021-02-18 13:47 UTC, ReneTode commented
> You need to format the code with black. Additionally, if you set up pre-commit correctly, this will be done on commit automatically (prevents you from running into these issues for the future).

i dont know how i format code with black, or how to setup pre-commit.

i just edited the files on github (in browser)

2021-02-19 13:30 UTC, Odianosen25 approved these changes

2021-02-19 14:36 UTC, Odianosen25 commented
@ReneTode, please can you add some docs for this?

Regards

2021-02-19 15:22 UTC, ReneTode commented
yeah, ill do that tommorrow.

2021-02-24 11:11 UTC, merged